[workspace]
resolver = "2"
members = [
    "programs/*",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
overflow-checks = false

[profile.release.build-override]
opt-level = "z"
incremental = false
codegen-units = 1